#include <iostream>  
#include <exception>  
using namespace std;  
class MyException : public exception{  
    public:  
        const char * what() const throw()  
        {  
            return "EXCEPTION Not possible";  
        }  
};  
int main()  
{  
    try  
    {  
        int x, y;  
        cin >> x >> y;  
        if (y == 0)  
        {  
            MyException z;  
            throw z;  
        }  
        else  
        {  
            cout <<"VALID"<< endl;  
        }  
    }  
    catch(exception& e)  
    {  
        cout << e.what();  
    }  
}  