#include <iostream>
using namespace std;
int main()
{
  cout<<"Start"<<endl;
  try{
    char s;
    cin>>s;
    cout<<"Inside try block."<<endl;
    throw s;
    cout<<"This will not execute."<<endl;
  }
  catch(char i){
    cout<<"Caught an exception value is="<<i<<endl;
  }
  cout<<"End"<<endl;
	return 0;
}