#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
char s;
cin>>s;
cout << "Start" << endl;
try {
cout << "Inside try block." << endl;

throw s;
cout << "This will not execute.";
}
catch(char i) {
cout << "Caught an exception value is="<<i<<endl;
}
cout << "End";
return 0;
}