#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
cout << "Start" << endl;
try {
char s;
cout << "Inside try block." << endl;
cin>>s;
throw s;
cout << "This will not execute.";
}
catch(char i) {
cout << "Caught an exception value is=";
cout << i << endl;
}
cout << "End";
return 0;
}