#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
  char ch;cin>>ch;
cout << "Start" << endl;
try {
char s;
cout << "Inside try block." << endl;

throw s;
cout << "This will not execute.";
}
catch(char i) {
cout << "Caught an exception value is="<<ch;
cout << i << endl;
}
cout << "End";
return 0;
}