{"Q_ID": "1319110001", "S_NAME": "Exceptional Handling", "Q_NAME": "Divide by zero error", "Q_DESC": "Get two integer values num1 and num2 from user and divide num1 by num2 if num2  is zero then the appropriate exception message needs to be displayed in the catch block.\n\nIf the num2 is non-zero then display as \"can be divided\"  \n\nMandatory:\n\n1. Use try and catch block to satisfy exceptional handling techniques.\n2. Inside catch method use the following class in the argument\n\ncatch(ArithmeticException e)\n\n3. Print the ArithmeticException object  \"e\" using \n\nSystem.out.println(e) and it will return the output as follows \"java.lang.ArithmeticException: / by zero\"", "TESTCASE_1": "12 4\n###---###SEPERATOR---###---\n3\ncan be divided", "TESTCASE_2": "55 5\n###---###SEPERATOR---###---\n11\ncan be divided", "TESTCASE_3": "0 19\n###---###SEPERATOR---###---\n0\ncan be divided", "TESTCASE_4": "25 0\n###---###SEPERATOR---###---\njava.lang.ArithmeticException: / by zero", "TESTCASE_5": " System.out.println(e);\n###---###SEPERATOR---###---\ncatch(ArithmeticException e)"}