{"Q_ID": "1319110009", "S_NAME": "Exceptional Handling", "Q_NAME": "Arithmetic exception", "Q_DESC": "Mandatory:\n\n1. Use try and catch block to satisfy exceptional handling techniques.\n2. Inside catch method use the following class in the argument\n\ncatch(ArithmeticException e)\n\n3. Print the ArithmeticException object  \"e\" using \n\nSystem.out.println(e) and it will return the output as follows \"java.lang.ArithmeticException: / by zero\"", "TESTCASE_1": "78\n12\n###---###SEPERATOR---###---\n6", "TESTCASE_2": "56\n0\n###---###SEPERATOR---###---\njava.lang.ArithmeticException: / by zero", "TESTCASE_3": "47\n3\n###---###SEPERATOR---###---\n15", "TESTCASE_4": "34\n0\n###---###SEPERATOR---###---\njava.lang.ArithmeticException: / by zero", "TESTCASE_5": "catch(ArithmeticException e)\n###---###SEPERATOR---###---\nSystem.out.println(e);\n"}