#include <iostream>
using namespace std;
int main()
{
  cout<<"Start"<<endl;
  try{
   int a;
    cout<<"Inside try block."<<endl;
    cin>>a;
    throw a;
  }
  catch(int i)
  {
  cout<<"Caught an exception value is=";
    cout<<i<<endl;
  }
 cout<<"End";
	return 0;
}