#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
  int n;
cout << "Start" << endl;
try {
int a;
cout << "Inside try block." << endl;
cin >>a;
throw a;
cout << "This will not execute.";
}
catch(int i) {
  cin>>n;
cout << "Caught an exception value is="<<n;
cout  << endl;
}
cout << "End";
return 0;
}