#include <iostream>
using namespace std;
int main()
{
  cout<<"Start";
  try{
    int a;
    cout<<"\nInside try block.";
    cin>>a;
    throw a;
    cout<<"\nThis will not execute.";
  }
  catch(int i)
  {
    cout<<"\nCaught an exception value is="<<i;
  }
  cout<<"\nEnd";
	return 0;
}