#include <iostream>
#include <math.h>
using namespace std;
int main()
{
  int x;
  cin>>x;
  cout<<"Start\nInside try block.\nCaught an exception value is="<<x<<endl<<"End";

	return 0;
}