#include <iostream>
using namespace std;
int main()
{
cout << "Start" << endl;
try
{
float s;
 cin>>s;
cout << "Inside try block." << endl;
throw s;
cout << "This will not execute.";
}
catch(float i)
{
cout << "Caught an exception value is="<<i;
cout << endl;
}
cout << "End";
return 0;
	}