#include <iostream>
#include<iomanip>
using namespace std;
int main()
{
  cout<<"Start\n";
  try
  {
    float s;
    cin>>s;
    cout<<"Inside try block.\n";
      throw s;
  }
  
catch(float p)
{
  cout<<"Caught an exception value is="<<p<<endl<<"End";
}
	return 0;
}