#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
cout << "Start" << endl;
try {
char s;
  float n;
  cin>>n;
cout << "Inside try block." << endl;

throw n;
cout << "This will not execute.";
}
catch(float i) {
cout << "Caught an exception value is=";
cout << i << endl;
}
cout << "End";
return 0;
}