#include<iostream>
using namespace std;
	int main ()
	{
      int n;
      cin>>n;
      
		try
		{
			throw n;
		}
		catch (int n)
		{
			cout<<"An exception occurred"<<endl;
			cout<<"Exception Number:"<<n;
		}
		return 0;
    }