#include <iostream>
using namespace std;
int main()
{
	int i;
  	try
    {
      cin>>i;
      cout<<"An exception occurred\n";
      throw(i);
    }
  	catch(int n)
    {
      cout<<"Exception Number:"<<n;
    }
	return 0;
}