#include <iostream>
using namespace std;
int main()
{
  try
  {
    int a;
    cin>>a;
    throw a;
  }
  catch(int a)
  {
    cout<<"An exception occurred"<<endl<<"Exception Number:"<<a;
  }
	return 0;
}