#include <iostream>
using namespace std;
int main()
{
  int a;
  try
  {
  cin>>a;
  throw a;
  }catch(int c)
  {
    cout<<"An exception occurred"<<endl;
      cout<<"Exception Number:"<<c;
  }

	return 0;
}