#include <iostream>
using namespace std;
int main()
{
float n;
  cin>>n;
  try
  {
    throw n;
  }
  catch(float p)
  {
    cout<<"An exception occurred"<<endl<<"Exception Number:"<<(int)p;
  }
	return 0;
}