#include <iostream>
using namespace std;
int main()
{
    int i;
    cin>>i;
    try{
      throw i;
    }
    catch(int x)
    {
      cout<<"An exception occurred";
      cout<<"\nException Number:"<<i;
    }
	return 0;
}