#include <iostream>
using namespace std;

void f1(int n){
	try{
    	throw n;
    }catch(int x){
    	cout<<"An exception occurred"<<endl;
      	cout<<"Exception Number="<<x<<endl;
    }	
}
void f2(string s){
	try{
    	throw s;
    }catch(string x){
    	cout<<"An exception occurred"<<endl;
      	cout<<"Exception string="<<x;
    }
}

int main()
{
	int n;
  	string s;
  	cin>>n>>s;
  	f1(n);
  	f2(s);
  
	return 0;
}