#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
cout << "Start" << endl;
try {
char s;
cout << "Inside try block." << endl;

throw s;
cout << "This will not execute.";
}
catch(char i) {
  char a[100];
 scanf ("%[^\n]", a);
cout << "Caught an exception value is="<<a;
cout << i << endl;
}
cout << "End";
return 0;
}