#include<iostream>
#include<cmath>
using namespace std;
int main(void)
{
cout << "Start" << endl;
try {
char s[20];
cout << "Inside try block." << endl;
cin.getline(s,20);
throw s;
cout << "This will not execute.";
}
catch(char i[20]) {
cout << "Caught an exception value is=";
cout << i << endl;
}
cout << "End";
return 0;
}