#include<iostream>
#include<string.h>
#include<cmath>
using namespace std;
int main(void)
{
   cout << "Start" << endl;
   char s[50];
   cin.get(s,50);
   try { 
          cout<<"Inside try block."<<endl;
          throw (s);
          cout <<"This will not execute.";
        }
        catch(char (s[50])){
                    cout<<"Caught an exception value is=";
                    cout <<s<< endl;
           }
      cout << "End";
      return 0;
}