#include <iostream>
using namespace std;
int main()
{
cout<<"Start"<<endl;
  try{
    string s;
    getline(cin,s);
    cout<<"Inside try block."<<endl;
    throw s;
    cout<<"This will not execute.";
  }
  catch(string i){
    cout<<"Caught an exception value is=";
    cout<<i<<endl;
  }
  cout<<"End";
	return 0;
}